// Generated by `pnpm design:tokens` from design/tokens.json — do not edit.
//
// Unified Design System v1 bridge for SwiftUI (see #249). Colors are
// dynamic NSColors that follow the effective appearance (light/dark).

import SwiftUI

public enum DesignTokens {
    // MARK: - Surfaces
    public static let surfaceWindow = dynamicColor(light: "#fafafa", dark: "#0b0b0d")
    public static let surfaceSunken = dynamicColor(light: "#f1f1f4", dark: "#0d0d10")
    public static let surfacePanel = dynamicColor(light: "#f5f5f7", dark: "#101013")
    public static let surfaceSurface = dynamicColor(light: "#ffffff", dark: "#131316")
    public static let surfaceRaised = dynamicColor(light: "#ececef", dark: "#1a1a1f")
    public static let surfaceOverlay = dynamicColor(light: "#ffffff", dark: "#161619")
    public static let surfaceRowHover = dynamicColor(light: "#efeff2", dark: "#16161a")

    // MARK: - Borders
    public static let borderDefault = dynamicColor(light: "#e1e1e6", dark: "#26262b")
    public static let borderStrong = dynamicColor(light: "#c9c9d2", dark: "#34343b")
    public static let borderFaint = dynamicColor(light: "#ececf1", dark: "#1e1e23")

    // MARK: - Text
    public static let textPrimary = dynamicColor(light: "#18181b", dark: "#f4f4f5")
    public static let textSecondary = dynamicColor(light: "#52525b", dark: "#9c9ca6")
    public static let textTertiary = dynamicColor(light: "#6e6e78", dark: "#71717a")
    public static let textDisabled = dynamicColor(light: "#a0a0ab", dark: "#5c5c66")
    public static let textDataBright = dynamicColor(light: "#27272a", dark: "#e4e4e7")
    public static let textLog = dynamicColor(light: "#3a3a44", dark: "#c8c8d0")

    // MARK: - Accent
    public static let accentDefault = dynamicColor(light: "#4e77e5", dark: "#6e9bf5")
    public static let accentAltViolet = dynamicColor(light: "#7c5ce8", dark: "#a78bfa")
    public static let accentAltTeal = dynamicColor(light: "#0f9e8e", dark: "#2dd4bf")

    // MARK: - Status
    public static let statusOk = dynamicColor(light: "#0a9a6b", dark: "#34d399")
    public static let statusWarn = dynamicColor(light: "#c47b09", dark: "#fbbf24")
    public static let statusErr = dynamicColor(light: "#dc3f3f", dark: "#f87171")
    public static let statusErrSolid = dynamicColor(light: "#c93535", dark: "#dc4646")
    public static let statusInfo = dynamicColor(light: "#0f7fbd", dark: "#7dd3fc")

    // MARK: - Cluster identity
    public static let clusterBlue = dynamicColor(light: "#3b82f6", dark: "#60a5fa")
    public static let clusterAmber = dynamicColor(light: "#d97706", dark: "#f59e0b")
    public static let clusterPink = dynamicColor(light: "#db2777", dark: "#f472b6")
    public static let clusterViolet = dynamicColor(light: "#7c3aed", dark: "#a78bfa")
    public static let clusterTeal = dynamicColor(light: "#0d9488", dark: "#2dd4bf")

    // MARK: - Spacing (pt)
    public static let spacing1: CGFloat = 4
    public static let spacing2: CGFloat = 8
    public static let spacing3: CGFloat = 12
    public static let spacing4: CGFloat = 16
    public static let spacing5: CGFloat = 20
    public static let spacing6: CGFloat = 24
    public static let spacing8: CGFloat = 32

    // MARK: - Radius (pt)
    public static let radiusSm: CGFloat = 4
    public static let radiusMd: CGFloat = 6
    public static let radiusLg: CGFloat = 8
    public static let radiusXl: CGFloat = 10
    public static let radius2xl: CGFloat = 12
    public static let radiusFull: CGFloat = 999

    // MARK: - Density (pt)
    public static let rowPadDefault: CGFloat = 9
    public static let rowPadCompact: CGFloat = 5
    public static let controlHeight: CGFloat = 28
    public static let minHitTarget: CGFloat = 28

    /// Appearance-aware color from light/dark hex pairs.
    private static func dynamicColor(light: String, dark: String) -> Color {
        Color(
            nsColor: NSColor(
                name: nil,
                dynamicProvider: { appearance in
                    let isDark =
                        appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
                    return NSColor(hex: isDark ? dark : light)
                }
            )
        )
    }
}

extension NSColor {
    /// `#rrggbb` hex parser used by the generated palette.
    convenience init(hex: String) {
        var value: UInt64 = 0
        Scanner(string: String(hex.dropFirst())).scanHexInt64(&value)
        self.init(
            srgbRed: CGFloat((value >> 16) & 0xff) / 255,
            green: CGFloat((value >> 8) & 0xff) / 255,
            blue: CGFloat(value & 0xff) / 255,
            alpha: 1
        )
    }
}
