// Generated by `pnpm design:tokens` from design/tokens.json — do not edit.
//
// Unified Design System v1.1 bridge for SwiftUI (see #249). Colors are
// dynamic NSColors that follow the effective appearance (light/dark).

import SwiftUI

public enum DesignTokens {
    // MARK: - Surfaces
    public static let surfaceWindow = dynamicColor(light: "#fafafa", dark: "#0b0b0d")
    public static let surfaceSunken = dynamicColor(light: "#f1f1f4", dark: "#0d0d10")
    public static let surfacePanel = dynamicColor(light: "#f5f5f7", dark: "#101013")
    public static let surfaceSurface = dynamicColor(light: "#ffffff", dark: "#131316")
    public static let surfaceRaised = dynamicColor(light: "#ececef", dark: "#1a1a1f")
    public static let surfaceOverlay = dynamicColor(light: "#ffffff", dark: "#161619")
    public static let surfaceRowHover = dynamicColor(light: "#efeff2", dark: "#16161a")

    // MARK: - Borders
    public static let borderDefault = dynamicColor(light: "#e1e1e6", dark: "#26262b")
    public static let borderStrong = dynamicColor(light: "#c9c9d2", dark: "#34343b")
    public static let borderFaint = dynamicColor(light: "#ececf1", dark: "#1e1e23")

    // MARK: - Text
    public static let textPrimary = dynamicColor(light: "#18181b", dark: "#f4f4f5")
    public static let textSecondary = dynamicColor(light: "#52525b", dark: "#9c9ca6")
    public static let textTertiary = dynamicColor(light: "#6e6e78", dark: "#7d7d86")
    public static let textDisabled = dynamicColor(light: "#9b9ba7", dark: "#5c5c66")
    public static let textDataBright = dynamicColor(light: "#27272a", dark: "#e4e4e7")
    public static let textLog = dynamicColor(light: "#3a3a44", dark: "#c8c8d0")

    // MARK: - Accent
    public static let accentDefault = dynamicColor(light: "#3b68e2", dark: "#6e9bf5")
    public static let accentAltViolet = dynamicColor(light: "#7756e7", dark: "#a78bfa")
    public static let accentAltTeal = dynamicColor(light: "#0c7e72", dark: "#2dd4bf")

    // MARK: - Status
    public static let statusOk = dynamicColor(light: "#087e58", dark: "#34d399")
    public static let statusWarn = dynamicColor(light: "#9b6107", dark: "#fbbf24")
    public static let statusErr = dynamicColor(light: "#d42727", dark: "#f87171")
    public static let statusErrSolid = dynamicColor(light: "#d35959", dark: "#d72929")
    public static let statusInfo = dynamicColor(light: "#0e74ad", dark: "#7dd3fc")

    // MARK: - Cluster identity
    public static let clusterBlue = dynamicColor(light: "#0b63f3", dark: "#60a5fa")
    public static let clusterAmber = dynamicColor(light: "#a65b05", dark: "#f59e0b")
    public static let clusterPink = dynamicColor(light: "#cf236f", dark: "#f472b6")
    public static let clusterViolet = dynamicColor(light: "#7c3aed", dark: "#a78bfa")
    public static let clusterTeal = dynamicColor(light: "#0b7b71", dark: "#2dd4bf")

    // MARK: - Spacing (pt)
    public static let spacing1: CGFloat = 4
    public static let spacing2: CGFloat = 8
    public static let spacing3: CGFloat = 12
    public static let spacing4: CGFloat = 16
    public static let spacing5: CGFloat = 20
    public static let spacing6: CGFloat = 24
    public static let spacing8: CGFloat = 32

    // MARK: - Radius (pt)
    public static let radiusSm: CGFloat = 4
    public static let radiusMd: CGFloat = 6
    public static let radiusLg: CGFloat = 8
    public static let radiusXl: CGFloat = 10
    public static let radius2xl: CGFloat = 12
    public static let radiusFull: CGFloat = 999

    // MARK: - Density (pt)
    public static let rowPadDefault: CGFloat = 9
    public static let rowPadCompact: CGFloat = 5
    public static let controlHeight: CGFloat = 28
    public static let minHitTarget: CGFloat = 28

    // MARK: - Icon sizes (pt)
    public static let icon2xs: CGFloat = 7
    public static let iconXs: CGFloat = 8
    public static let iconSm: CGFloat = 10
    public static let iconMd: CGFloat = 11

    // MARK: - Typography (type scale v1.1)
    public enum Typography {
        /// One design-system text style. `tracking` is a fraction of the font
        /// size (em). Apply with `View.typeStyle(_:color:)`.
        public struct Style: Sendable, Equatable {
            public let size: CGFloat
            public let weight: Font.Weight
            public let mono: Bool
            public let uppercase: Bool
            public let tracking: CGFloat
        }

        public static let display = Style(size: 28, weight: .semibold, mono: false, uppercase: false, tracking: 0)
        public static let title = Style(size: 16, weight: .semibold, mono: false, uppercase: false, tracking: 0)
        public static let subtitle = Style(size: 13.5, weight: .semibold, mono: false, uppercase: false, tracking: 0)
        public static let body = Style(size: 13, weight: .medium, mono: false, uppercase: false, tracking: 0)
        public static let caption = Style(size: 11.5, weight: .regular, mono: false, uppercase: false, tracking: 0)
        public static let section = Style(size: 10, weight: .semibold, mono: false, uppercase: true, tracking: 0.07)
        public static let colhead = Style(size: 11, weight: .semibold, mono: false, uppercase: true, tracking: 0.05)
        public static let data = Style(size: 12.5, weight: .medium, mono: true, uppercase: false, tracking: 0)
        public static let dataSm = Style(size: 12, weight: .regular, mono: true, uppercase: false, tracking: 0)
        public static let log = Style(size: 11.5, weight: .regular, mono: true, uppercase: false, tracking: 0)
        public static let stat = Style(size: 22, weight: .semibold, mono: true, uppercase: false, tracking: 0)
        public static let micro = Style(size: 10.5, weight: .medium, mono: false, uppercase: false, tracking: 0)

        /// Every style, in token order — for lint-style tests.
        public static let all: [(name: String, style: Style)] = [
            (name: "display", style: display),
            (name: "title", style: title),
            (name: "subtitle", style: subtitle),
            (name: "body", style: body),
            (name: "caption", style: caption),
            (name: "section", style: section),
            (name: "colhead", style: colhead),
            (name: "data", style: data),
            (name: "dataSm", style: dataSm),
            (name: "log", style: log),
            (name: "stat", style: stat),
            (name: "micro", style: micro),
        ]
    }

    /// Appearance-aware color from light/dark hex pairs.
    private static func dynamicColor(light: String, dark: String) -> Color {
        Color(
            nsColor: NSColor(
                name: nil,
                dynamicProvider: { appearance in
                    let isDark =
                        appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
                    return NSColor(hex: isDark ? dark : light)
                }
            )
        )
    }
}

extension NSColor {
    /// `#rrggbb` hex parser used by the generated palette.
    convenience init(hex: String) {
        var value: UInt64 = 0
        Scanner(string: String(hex.dropFirst())).scanHexInt64(&value)
        self.init(
            srgbRed: CGFloat((value >> 16) & 0xff) / 255,
            green: CGFloat((value >> 8) & 0xff) / 255,
            blue: CGFloat(value & 0xff) / 255,
            alpha: 1
        )
    }
}
