[package]
name = "cubelite-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
dirs = { workspace = true }
kube = { workspace = true, features = ["oidc"] }
serde_json = { workspace = true }
k8s-openapi = { workspace = true }
base64 = "0.23"
http = "1"
flate2 = "1"

[dev-dependencies]
tempfile = "3"
serial_test = "4"
